modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"

[[mods]]
modId="null_ouroboros"
version="1.0"
displayName="NULL OUROBOROS"
authors="Destiny"
description='Temp description'
logoFile="assets/null_ouroboros/textures/misc/logo.png"

[[dependencies.null_ouroboros]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.null_ouroboros]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.null_ouroboros]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.9, )"
    ordering="NONE"
    side="BOTH"